TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3

  max_vel_theta: 0.4
  min_vel_theta: -0.4

  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_theta: 0.5

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

  sim_time: 2.0 #0.8
  sim_granularity: 0.025
  angular_sim_granularity: 0.025

  vx_samples: 8
  vy_samples: 0
  vtheta_samples: 20

  path_distance_bias: 5.0
  goal_distance_bias: 15.0
  occdist_scale: 0.01

  heading_lookahead: 0.5
  oscillation_reset_dist: 0.1
  escape_reset_dist: 0.2
  escape_reset_theta: 0.2
